# Generated by Django 5.0.14 on 2025-12-07 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('valid_from', models.DateTimeField(verbose_name='Действителен с')),
                ('valid_to', models.DateTimeField(verbose_name='Действителен до')),
                ('usage_limit', models.IntegerField(blank=True, default=None, null=True, verbose_name='Лимит использований')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Минимальная сумма покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название праздника')),
                ('holiday_type', models.CharField(choices=[('new_year', 'Новый Год'), ('christmas', 'Рождество'), ('easter', 'Пасха'), ('black_friday', 'Черная Пятница'), ('valentines', 'День Святого Валентина'), ('womens_day', 'Международный Женский День'), ('cyber_monday', 'Киберпонедельник'), ('summer_sale', 'Летняя Распродажа'), ('custom', 'Кастомный Праздник')], max_length=50, verbose_name='Тип праздника')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товара')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оригинальная цена')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='discounts.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-created_at'],
                'unique_together': {('product_id', 'holiday')},
            },
        ),
    ]
