# Generated by Django 5.2.5 on 2025-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3, verbose_name='Базовая валюта')),
                ('target_currency', models.CharField(max_length=3, verbose_name='Целевая валюта')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Курс обмена')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['base_currency', 'target_currency'],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
